// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3QU95ZK8Nrv-KMB3_Hea9s2RkZczGJQo',
    appId: '1:472814168339:web:b79291801d3852061d92e6',
    messagingSenderId: '472814168339',
    projectId: 'assignmentwandoor',
    authDomain: 'assignmentwandoor.firebaseapp.com',
    storageBucket: 'assignmentwandoor.appspot.com',
    measurementId: 'G-YVH0LZNZN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmPsDRrlwue9mLHK81PuveU28fuqR3jMI',
    appId: '1:472814168339:android:77e59093066558621d92e6',
    messagingSenderId: '472814168339',
    projectId: 'assignmentwandoor',
    storageBucket: 'assignmentwandoor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqWvKtVcYcbtVPYgoYxgPxqzeguWArdzQ',
    appId: '1:472814168339:ios:5567002e922923db1d92e6',
    messagingSenderId: '472814168339',
    projectId: 'assignmentwandoor',
    storageBucket: 'assignmentwandoor.appspot.com',
    androidClientId: '472814168339-9r5se8vev2q7iib0n40m12bank75600r.apps.googleusercontent.com',
    iosClientId: '472814168339-snjpaind558nohk7rdruusuurqvqtlk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.agoraZikrabyte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqWvKtVcYcbtVPYgoYxgPxqzeguWArdzQ',
    appId: '1:472814168339:ios:fa1c4f49d60da5e71d92e6',
    messagingSenderId: '472814168339',
    projectId: 'assignmentwandoor',
    storageBucket: 'assignmentwandoor.appspot.com',
    androidClientId: '472814168339-9r5se8vev2q7iib0n40m12bank75600r.apps.googleusercontent.com',
    iosClientId: '472814168339-jn93ub1493t30iipaeddnqh50gacguvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.agoraZikrabyte.RunnerTests',
  );
}
